---


main_user: amoussi
user_home: "/home/{{main_user}}"
k8s_networks_dir: "{{user_home}}/k8s/networks"

k8s_networking_files_urls:
  - https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
  - https://docs.projectcalico.org/latest/manifests/calico.yaml

k8s_networking_files:
  - "{{k8s_networks_dir}}/rbac-kdd.yaml"
  - "{{k8s_networks_dir}}//calico.yaml"



pod_network_cidr: 192.168.0.0/16

k8s_admin_config_file: /etc/kubernetes/admin.conf